//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sinnombre
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int idusuario { get; set; }
        public string nombre { get; set; }
        public string Apellidos { get; set; }
        public string sexo { get; set; }
        public Nullable<System.DateTime> fecha_nac { get; set; }
        public string tipodoc { get; set; }
        public string num_doc { get; set; }
        public string direccion { get; set; }
        public string nacionalidad { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public string Usuario1 { get; set; }
        public string claveusu { get; set; }
    }
}
